### ISSUE TITLE
Explicit type cast required for malloc/calloc in some C++ compiler

### ISSUE THREAD

**Issue by syoyo** [prideout/par#1]
Some C++ compiler(e.g. MacOSX's default clang++) reports an error when compiling par_msqures.h(and other .h which uses malloc/calloc) with C++ codes, for example:

```
./par_msquares.h:255:28: error: cannot initialize a variable of type 'par_msquares_meshlist *' (aka 'par_msquares_meshlist_s *')
      with an rvalue of type 'void *'
    par_msquares_meshlist* merged = malloc(sizeof(par_msquares_meshlist));
                           ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

It would be nice to add explicit type cast for malloc/calloc(or functions returning void pointer) to `par_***.h`

**Comment by prideout** [comment]
Ah, thanks for pointing this out.  Alas, C is not a subset of C++.  I fixed this with a PAR_ALLOC macro and added a C++ test to Travis, so it should be good now!

**Comment by syoyo** [comment]
Cool! Thanks!
