### ISSUE TITLE
Linkage not compatible between C and C++ translation units

### ISSUE THREAD

**Issue by zao** [prideout/par#10]
While the code compiles as either C and C++, the mangling of the functions differs partially between the languages, which means you have to decide when building the source file that contains the implementation if it's to be used in C or C++ source files in the project.

STB solves this in his libraries by wrapping the code in the following, which ensures a consistent "C" linkage:

    #ifdef __cplusplus
    extern "C" {
    #endif

**Comment by philip-napofearth** [comment]
This is a really good suggestion, I'll go ahead and make this change across all the par libraries.

**Comment by astoeckley** [comment]
Nice!  I had manually added these extern lines myself to the files i'm using from this repository, but I look forward to using the actual original file instead.
