### ISSUE TITLE
Possible error in fread call in par_bluenoise

### ISSUE THREAD

**Issue by JaapSuter** [prideout/par#11]
In par_bluenoise.h line 337 the code does:

    int consumed = (int) fread(buf, nbytes, 1, fin);
    assert(consumed == nbytes);

I believe that `fread` is defined to be something akin to:

    size_t fread(void *ptr, size_t size, size_t count, FILE *stream);

Note the order of the size (of a single element, in bytes) and count (number of elements to read).

This means that the call to `fread` as you have it, is reading a single element of `nbytes` size. The end-result is pretty much the same from a bytes in memory point of view. But for the assert immediately following it, it's a bit of a problem (since `nconsumed` will be equal to 1.)

(I'd send you a pull request instead, but I don't have a great git setup at hand, and the fix is rather easy anyway. That is, if I'm not mistaken of course.)

Thanks,

Jaap Suter - http://jaapsuter.com

**Comment by philip-napofearth** [comment]
Ah, good catch.  The assertion should check `consumed` against 1 rather than `nbytes`.  I will fix this.
