### ISSUE TITLE
shapes: Division by zero in par_shapes_weld

### ISSUE THREAD

**Issue by Spasi** [prideout/par#12]
The function `par_shapes_weld` computes a scale factor based on the mesh AABB. This computation may produce `NaNs` (and does for `par_shapes_create_plane`) when the input mesh is "flat", i.e. the AABB has zero width on at least one axis.

A simple fix could be:

```c
float scale[3] = {
    aabb[3] == aabb[0] ? 1.0 : maxcell / (aabb[3] - aabb[0]),
    aabb[4] == aabb[1] ? 1.0 : maxcell / (aabb[4] - aabb[1]),
    aabb[5] == aabb[2] ? 1.0 : maxcell / (aabb[5] - aabb[2]),
};
```

**Comment by prideout** [comment]
Thanks, good catch!  Indeed, I can see `NaNs` in the plane mesh generated by the unit tests.  Will fix.
