### ISSUE TITLE
Smooth normals?

### ISSUE THREAD

**Issue by rogerdahl** [prideout/par#13]
Thank you for the par library! I'm trying to use some meshes generated with par_shapes with a phong shader, but I'm getting flat triangles. So it looks like the normals are all the same for each triangle. However, I see references to "smooth normals" in the instructions and the front sphere in the image of the three types of spheres appears to be smooth. I think my shader requires each normal to point out from the center of the sphere. Is that what the library provides?

I've tried the parametric_sphere, subdivided_sphere and other shapes both with and without `unweld()` and `compute_normals()`.

**Comment by prideout** [comment]
Hi Roger,

If you simply use `par_shapes_create_parametric_sphere`, then smooth normals will definitely be present in the resulting `mesh->normals` field.  This is the case with all parametric shapes; there's no need to call `unweld()` or `compute_normals()`.

Note that the values in `mesh->normals` are intended for lighting only.  If the mesh silhouette is more faceted that you'd like, smooth normals won't help.  The only way to create smooth _geometry_ is to increase the LOD value(s) that you pass to the create function.

Does this help?

**Comment by rogerdahl** [comment]
Thank you for the reply. I've done some more experiments now and the results are probably due to one or more bugs on my side. Here's what I'm currently seeing, in case this makes any sense to you :)

Without `unweld()` and without `compute_normals()`:
https://drive.google.com/file/d/0BwBD6O94XERdNW5GbnNkVkx5NEU/view?usp=sharing

With only `unweld()`:
https://drive.google.com/file/d/0BwBD6O94XERdQVdJOHdsRy01cG8/view?usp=sharing
Notice the elliptical highlights.

With both `unweld()` and `compute_normals()`:
https://drive.google.com/file/d/0BwBD6O94XERdU2pJME9mQzRpSmc/view?usp=sharing
Notice the flat triangles on the left side. Earlier, I had the light set so that I only saw these, which is why I suspected the normals.

**Comment by rogerdahl** [comment]
The issue was that I didn't know about the face-vertex format for meshes and expected just a plain array of points.

**Comment by rogerdahl** [comment]
I was going to add a couple of lines to the doc for par_shapes, but I see now that it's not part of the repo. Basically, something like:

Meshes are returned in a face-vertex format. The `triangles` array contains indexes into the `points` and `normals` arrays. Also see https://en.wikipedia.org/wiki/Polygon_mesh#Face-vertex_meshes.
