### ISSUE TITLE
[shapes] please add capsule to par_shapes

### ISSUE THREAD

**Issue by powof2** [prideout/par#19]
hi, thank you for the great job.

can you add capsule to par_shapes? because it is widely used in physics to represent player/character shapes, thank you.

**Comment by sonoro1234** [comment]
this is LuaJIT code to generate capsule
C conversion should be easy
```
local slices = 20
mesh = par_shapes.create.empty()
local cyl = par_shapes.create.cylinder(slices, 2);
local hemis = par_shapes.create.hemisphere(slices,10)
mesh:merge(hemis)
cyl:rotate(math.pi*0.5,floats(1,0,0))
cyl:scale(1,2,1)
mesh:merge(cyl)
local hemis_c = hemis:clone(nil)
hemis_c:rotate(math.pi,floats(1,0,0))
hemis_c:translate(0,-2,0)
mesh:merge(hemis_c)
```

**Comment by prideout** [comment]
This is a good idea; I suspect that physics engines internally represent capsules using a non-triangulated representation but this could be useful rendering purposes.

**Comment by prideout** [comment]
I'm going to close this since it can be achieved by combining a cylinder and hemisphere, which should be good enough for rendering purposes, and "rendering purposes" is the only reason you'd want a triangulated capsule.  (Having said all that, I'd probably accept a PR for this feature.)
