### ISSUE TITLE
[shapes] Support texture coordinates

### ISSUE THREAD

**Issue by raysan5** [prideout/par#21]
I've noticed that default texture coordinates are not being generated for some shapes. It would be great some default texture coordinates could be generated, at least for basic meshes (cube, cillinder, torus...).

Or maybe provide some function to generate texture coordinates, like normals generation.

Congrats for the library, it's amazing! I'm planning to add meshes generation to [raylib](https://github.com/raysan5/raylib) using it! :)

EDIT: Just seen sphere provides texcoords, miss it for cube and other basic shapes...

**Comment by raysan5** [comment]
Just took some more time to analyze and use the library...

Noticed that default texture coordinates are just missing for "platonic solids", disk shape, subdivided spheres and misc shapes.

It would be useful a function to generate some default texcoords for those shapes, specially useful for cubes, pyramids and spheres.

Also missing the possibility to generate cones... It would be useful for raylib function:
```c
Mesh GenMeshCylinder(float radiusTop, float radiusBottom, float height, int slices);
```

**Comment by sonoro1234** [comment]
create parametric is so usefull
this is LuaJIT code but can be easyly translated to C
one radius is 1 the other r2
inv is a bool meaning inverted
```
function par_shapes.create.cone_trunk(a,b,r2,inv)
	return lib.par_shapes_create_parametric(function(inp,out,us) 
		local u = math.pi * 2 * inp[1]
		local v
		if inv then
			v = inp[0]
		else
			v = 1 - inp[0]
		end
		v = r2 + v*(1-r2)
		out[0] = v * math.sin(u)
		out[1] = v * math.cos(u)
		out[2] = inp[0]
	end,a,b,nil)
end
```

**Comment by prideout** [comment]
Platonic solids do not have an obvious surface parameterization, so this limitation is by design.
