### ISSUE TITLE
Acknowledgement as plugin

### ISSUE THREAD

**Issue by ggcrunchy** [prideout/par#23]
Hi. This isn't an "issue", exactly, but I didn't see a contact e-mail.

I've wrapped up a plugin based on **msquares** for [Corona SDK](https://coronalabs.com) and am trying to flesh out the [docs](https://ggcrunchy.github.io/corona-plugin-docs/DOCS/msquares/api.html), which I imagine will largely draw from your blog post. I've basically kept the same API, though there might be a few concessions to play well with Lua. (It's been a little well since I first bound it, so I'd have to review.)

The plugin listing will also include an icon. (This would default to the company icon I provided for myself.) Any preference here? I was thinking maybe the "island" next to the "Marching Squares" blog post [here](http://github.prideout.net), but wanted to run it by you first. (Alternatively, the grasshopper or some variation on it.)

(I've had my eye on a few other libraries, too.)

**Comment by prideout** [comment]
I'm honored that this will go into Corona!  I think using the island icon would be nice.

**Comment by ggcrunchy** [comment]
Awesome, thanks. I'll write back here whenever it goes live, ideally in a couple weeks.

**Comment by ggcrunchy** [comment]
Well, it took rather longer than expected (a couple things came up, suffice to say) but it's live with a couple examples: [link](https://marketplace.coronalabs.com/corona-plugins/msquares) I'll try to add a few more for grayscale and friends too.

It does look like it will crash if no bytes are assigned (easy enough to do with the drag-on-image + button UI here). I'll see if I can pin that down.
