### ISSUE TITLE
compute_welded_normals in bunny.ctm

### ISSUE THREAD

**Issue by sonoro1234** [prideout/par#31]
Related to #30 

When loading this ctm mesh:

[bunny.zip](https://github.com/prideout/par/files/3729780/bunny.zip)

compute_welded_normals dont crash (as in #30) but there are normals not correctly calculated.
It can be avoided by recompiling par_shapes with
https://github.com/prideout/par/blob/master/par_shapes.h#L305
replaced by ` par_shapes_mesh* welded = par_shapes_weld(m, 0.001, weldmap);`

So changing epsilon to a smaller size will not weld different position points.
It also makes #30 to happen only for higher values of slices and stacks.

I think it would be useful to provide access to the epsilon value, it could be done making it an argument to `par_shapes__compute_welded_normals` and to `par_shapes_create_parametric`

What do you think?
Shall I do a PR for that?

**Comment by prideout** [comment]
Yes let's make epsilon configurable.  To keep the API simple I think I would prefer a "global config" rather than adding new arguments to those functions.  I will make the PR.
