### ISSUE TITLE
install

### ISSUE THREAD

**Issue by adammaj1** [prideout/par#36]
Hi. 

Some notes about installation:

> sudo apt-get install libcurl4-gnutls-dev
git clone https://github.com/prideout/par
cd par
cmake test -Bbuild 
cd build
cmake .
make
./test_bubbles

  par_bubbles_pack
Memory protection violation

**Comment by prideout** [comment]
The unit tests only work if your current working directory is the repo root.  Made this somewhat more friendly with 4e9236f.
