### ISSUE TITLE
par_shapes_create_parametric_sphere() loses "equator" when calling par_shapes_remove_degenerate()?

### ISSUE THREAD

**Issue by Roflraging** [prideout/par#4]
I've been trying to use the sphere mesh to help visualize things in the game I am working on, but I noticed that the parametric sphere seems to have triangles at the "equator" missing:

![untitled](https://cloud.githubusercontent.com/assets/3121968/12406750/948231ca-be15-11e5-9c2c-dfdfb66fc585.png)

But if I go into `par_shapes_create_parametric_sphere()` and remove the call to `par_shapes_remove_degenerate()` then I get this:
![untitled2](https://cloud.githubusercontent.com/assets/3121968/12406753/999bbc4e-be15-11e5-938a-eff4a2b91f3b.png)

The call is simply `par_shapes_create_parametric_sphere(16, 16)`.  Am I doing something bad here?  Feels like I shouldn't need to remove this call.

**Comment by philip-napofearth** [comment]
Oh, maybe we need to adjust epsilon according to scale.  I'll take a look.
