### ISSUE TITLE
The triangles data in par_shapes

### ISSUE THREAD

**Issue by astoeckley** [prideout/par#5]
Hi Mr Rideout
big fan of your iphone book. Now i'm enjoying this library par_shapes. Please forgive me for a basic question, but I noticed that ```par_shapes_create_subdivided_sphere(1)``` returns with ```ntriangles``` as ```80```. I am gathering that the triangle integers returned are indices into the ```points``` array, but it's not clear why this number is not a multiple of 3. I was assuming that each 3 indices in ```triangles``` is a single triangle, and then the next 3 are the next triangle.. but then, shouldn't there be enough points to supply whole triangles? Or, are the last 2 points supposed to be joined with the original first point to create the final triangle?

**Comment by prideout** [comment]
Thanks for the question @astoeckley!  `ntriangles` is the number of triangles, not the number of integers.   The total number of integers in the `triangles` array is `3 * ntriangles`.

> I was assuming that each 3 indices in triangles is a single triangle, and then the next 3 are the next triangle.

This is correct.

**Comment by astoeckley** [comment]
Got it! Thanks for the clarification. Out of habit I was thinking that the count of an array is typically the number that is passed around. I realize now that I was also missing this with the number of points; it should be triple how I was interpreting it.
