### ISSUE TITLE
Having trouble with subdivided sphere with `nsubd > 5` and Raylib

### ISSUE THREAD

**Issue by dejaime** [prideout/par#52]
Hi,

I'm trying to use `par_shapes_create_subdivided_sphere` but am having some trouble. 
The shape seems to work fine up to 5 subdivisions. When I use `nsubd` of 6 or higher though, it breaks.

![icosphere](https://user-images.githubusercontent.com/2046959/123479482-62f76f00-d5d7-11eb-8f4d-9ca23b28568a.gif)

The code I'm using to translate the shape information seems to be correct, this is the relevant part:

```cpp
//Generate mesh function
Mesh GenMeshIcosphere(int subdivisions) {
    assert(subdivisions > 0 && "Trying to create IcoSphere mesh with subdivisions <= 0");

    Mesh mesh; // raylib mesh struct
    par_shapes_mesh *sphere = par_shapes_create_subdivided_sphere(subdivisions);

    // Allocating mem for geometry info
    //    texcoords are not generated in previous par_shapes call
    mesh.vertices = (float *)RL_MALLOC(sphere->ntriangles * 3 * 3 * sizeof(float));
    mesh.normals = (float *)RL_MALLOC(sphere->ntriangles * 3 * 3 * sizeof(float));

    mesh.vertexCount = sphere->ntriangles * 3;
    mesh.triangleCount = sphere->ntriangles;

    for (int k = 0; k < mesh.vertexCount; k++) {
        mesh.vertices[k * 3] = sphere->points[sphere->triangles[k] * 3];
        mesh.vertices[k * 3 + 1] = sphere->points[sphere->triangles[k] * 3 + 1];
        mesh.vertices[k * 3 + 2] = sphere->points[sphere->triangles[k] * 3 + 2];

        mesh.normals[k * 3] = sphere->normals[sphere->triangles[k] * 3];
        mesh.normals[k * 3 + 1] = sphere->normals[sphere->triangles[k] * 3 + 1];
        mesh.normals[k * 3 + 2] = sphere->normals[sphere->triangles[k] * 3 + 2];
    }

    par_shapes_free_mesh(sphere);

    UploadMesh(&mesh, false);
    return mesh;
}
```
This is based on the way Raylib uses `par_shapes.h` on its mesh functions, as can be seen [here](https://github.com/raysan5/raylib/blob/e0720a0a5577cfb69ecb34fb4bd89e59f40f6b29/src/models.c#L1889),  and seems to work up to 5 subdivisions.

The broken shape is consistent, and breaks in exactly the same way every time. At first, it seemed to be some kind of accidental memory overwrite; but I'm starting to think it might not be on my side. 

Does `par_shapes_create_subdivided_sphere` have a limit on subdivisions? Any chance the problem is not on my side?

Thank you very much!

**Comment by prideout** [comment]
Hm, I'm not sure but one theory is that 16-bit integers are used by default.  You can try this before include par_shapes:

#define PAR_SHAPES_T uint32_t

**Comment by dejaime** [comment]
Thank you for your answer! It's definitely something to do with that! I added the define but now I can't read the `points` array anymore, for any `nsubd` value. This is what GDB gives me:

![image](https://user-images.githubusercontent.com/2046959/123485707-0305c600-d5e1-11eb-9438-8c15ba7161d8.png)

```cpp
	par_shapes_mesh *sphere = par_shapes_create_subdivided_sphere(1); // Testing arbitrarily with 1

	std::cout<<sphere->npoints<<std::endl; // <--- Debugger shows values in this line
	std::cout<<sphere->points[1]<<std::endl; // <--- signal SIGSEGV (Address boundary error)
```

I'm not really sure what caused this. I'll double check my code and see if I'm doing something wrong that may be causing that to  the points array.

**Comment by dejaime** [comment]
the first value of `sphere->triangles` is really high numbers like `742754`, what I didn't expect in a 1 subdivision icosphere. I think I misunderstood something on how `par_shapes_mesh` is built, I'll close this for now and reopen if I hit any problems!

Thank you for the tip!
