### ISSUE TITLE
Recommended # of subdivisions

### ISSUE THREAD

**Issue by astoeckley** [prideout/par#6]
I can draw the points from this fine:

par_shapes_create_subdivided_sphere(5)

but the following change eats up all the memory and crashes the app with a malloc error, and Google and Stackoverflow results suggest it is because a tremendous amount of memory is being allocated:

par_shapes_create_subdivided_sphere(10)

Is there a good way to know what the reasonable limits are for the various parameters of the library?

**Comment by prideout** [comment]
Each level of subdivision multiplies the number of triangles by four.  So, 3 subdivisions means 64x the number of original triangles.  I recommend using low numbers, e.g., less than 4.  I'll go ahead and update the header file to include a comment that warns clients about this.  Thanks for pointing this out.

**Comment by astoeckley** [comment]
Thanks!
