### ISSUE TITLE
shapes: L-system has incomplete normals and tcoords

### ISSUE THREAD

**Issue by Spasi** [prideout/par#7]
Looks like the problem is in `par_shapes__connect`. It should be copying normals and texture coordinates as well, not only positions.

**Comment by philip-napofearth** [comment]
Good point.  Not all shape generators in `par_shapes` provide normals and tcoords (e.g., polyhedra), so maybe the simplest "fix" for now would be to clearly document the L-system API, so that users are warned of this limitation.
