### ISSUE TITLE
shapes: Support custom allocation functions

### ISSUE THREAD

**Issue by Spasi** [prideout/par#8]
There are two problems currently:

- There are many direct calls to the stdlib functions. All `malloc/calloc/realloc/free` calls should be replaced with `PAR_MALLOC/PAR_CALLOC/PAR_REALLOC/PAR_FREE` respectively.
- It'd be more convenient to decouple the allocation functions from `PAR_HELPERS`. Right now you're forced to redefine all other helper functions if you want to override the allocation functions. Something like:

```c
#ifndef PAR_MALLOC
#define PAR_MALLOC(T, N) ((T*) malloc(N * sizeof(T)))
#define PAR_CALLOC(T, N) ((T*) calloc(N * sizeof(T), 1))
#define PAR_REALLOC(T, BUF, N) ((T*) realloc(BUF, sizeof(T) * N))
#define PAR_FREE(BUF) free(BUF)
#endif
```

would be great.

**Comment by philip-napofearth** [comment]
This is a great idea.

**Comment by Spasi** [comment]
Thanks! There are still several free() calls in there though, could you replace them with PAR_FREE please?

**Comment by philip-napofearth** [comment]
Done.
