### ISSUE TITLE
Inside of torus shows through outside, only from one orientation

### ISSUE THREAD

**Issue by astoeckley** [prideout/par#9]
Hello Philip! 
I do say, good day to you again sir!
I am having one peculiarity with the torus in par_shapes; I do not have this issue with any of the other shapes. When I rotate the torus, on one side the center properly is out of view by the outer edge. But 180 degrees flipped, the center shows through. I've experimented with various GL culling and depth settings, but I thought I'd ask here if possibly the triangles on the inside are not winding correct to cull them correctly? (If that's even the right terminology or concept). Here is what I'm seeing:

<img width="366" alt="screen shot 2016-01-28 at 06 41 37" src="https://cloud.githubusercontent.com/assets/4611759/12636141/95554c1e-c58a-11e5-9f12-346ce2029855.png">

<img width="371" alt="screen shot 2016-01-28 at 06 44 38" src="https://cloud.githubusercontent.com/assets/4611759/12636149/a41dbb32-c58a-11e5-951f-a9045b8c6ff2.png">

Many thanks for a neat little library.

**Comment by astoeckley** [comment]
For good measure, here is how it looks correctly when I flip it 180 degrees:

<img width="365" alt="screen shot 2016-01-28 at 07 12 57" src="https://cloud.githubusercontent.com/assets/4611759/12636625/9f46944a-c58e-11e5-9dcd-635be110b4d7.png">

**Comment by philip-napofearth** [comment]
Interesting.  The winding direction of the torus triangles appears fine both in MeshLab and in my own renderer, so I'm tempted to point the evil finger of blame towards your renderer.  :)  But, I might be wrong.  Here are my suggestions:

- Ensure that depth testing is enabled, and that your framebuffer has a depth plane.
- Ensure that your depth buffer is cleared on every frame.
- If culling is enabled, ensure that you're using GL's default settings (cull backfaces, frontfaces are CCW)

Philip

**Comment by astoeckley** [comment]
Thanks for the help, you nailed it. I am using GLKit on iOS and forgot a key line that made all the difference:

view.drawableDepthFormat = GLKViewDrawableDepthFormat24;

I wouldn't have looked there without your comment, so many thanks! All the other shapes looked great even without this line, so I thought there was an issue specific to the torus.
